### ISSUE TITLE
Modrinth release ?

### ISSUE THREAD

**Issue by Enderteck** [zlainsama/CosmeticArmorReworked#108]
Will this mod be published to modrinth ? I'd love to see it there.

Modritnh is Open source, rapidly growing and promises good developper compensation:

https://blog.modrinth.com/p/capital-return

You would be giving back to the comunity instead of Overwolf

Thanks in advance.

**Comment by Cyanide-1** [comment]
I came here to leave the same thing, a modrinth release would make it much easier to add this mod to my modpack. Im currently having to manually import files. Would make it much easier.

**Comment by devingDev** [comment]
Also wondering why there is no modrinth release since most of our mods in our modpack are from modrinth 😢

**Comment by zlainsama** [comment]
Well... I am still uploading my mods manually, although most of them are just once per Minecraft update, adding Modrinth to this would mean x2 of this process... and that's actually not much work, I will consider uploading to Modrinth.
By the way, if I chose to uploading to Modrinth, what versions of Minecraft would you want me to upload?

**Comment by Enderteck** [comment]
> Well... I am still uploading my mods manually, although most of them are just once per Minecraft update, adding Modrinth to this would mean x2 of this process... and that's actually not much work, I will consider uploading to Modrinth. By the way, if I choose to upload to Modrinth, what versions of Minecraft would you want me to upload?

1.12.2 1.16.5 1.18.2 1.19.2 1.20.1 and 1.21.

1.20+ versions should probably be the priority.

Most big mods now upload mostly to modrinth, makes sense, if you create an open source mod, distribting it on an open source platform that gives better dev compensation is the right move.

**Comment by vaporvee** [comment]
any news on this ? really like this mod :)

**Comment by Alphaluck** [comment]
Came here to see if the question had been asked, so I'm also asking if there's been any further consideration! It would make it a lot easier to put this in a Modrinth modpack.

**Comment by zlainsama** [comment]
I don't have a plan to upload to Modrinth right now. I might consider uploading to Modrinth in future.
You are allowed to use my mods in Modrinth modpacks. Please don't upload my mods as your own projects.

**Comment by OffsetMonkey538** [comment]
Automatic publishing is pretty easy btw, you can use the `minotaur` gradle plugin and then specify all the metadata in the `modrinth` block in your build.gradle file. Then you can have a basic github workflow that runs on release creation and runs the `modrinth` gradle task. I've never published to curseforge, but I'm pretty sure they also have a gradle plugin for publishing, so you could make publishing there simpler as well.

```gradle
modrinth {
	// Main properties
	token = System.getenv("MODRINTH_TOKEN") // MODRINTH_TOKEN has to be set as an env variable in the github workflow
	projectId = "modid"
    gameVersions = [
            "1.21.1",
            "1.21.2"
    ]

	// Version stuff
	def customVersionName = System.getenv("VERSION_NAME") // version name specified by github workflow
	if (customVersionName != null) versionName = customVersionName
	versionNumber = "${project.version}"

	// Files
	uploadFile = remapJar.archiveFile
	additionalFiles = [sourcesJar.archiveFile]


	// Project info
	syncBodyFrom = rootProject.file("README.md").text // syncs readme to modrinth automatically
	def changelogEnv = System.getenv("VERSION_CHANGELOG") // changelog text is added in the github workflow
	if (changelogEnv != null) changelog = changelogEnv

	dependencies {
		required.project "fabric-api" // whatever is required
	}
}

// makes it sync the description when the `modrinth` task is run
tasks.modrinth.dependsOn(tasks.modrinthSyncBody)
```

```yml
name: Publish the mod

on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar

      - name: Upload to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_NAME: ${{ github.event.release.name }}
          VERSION_CHANGELOG: ${{ github.event.release.body }}
```
